// **************        variabels created          ************
// this variable stores the random number generated by the ranNum function
let compNum;
// this variable stores the value of the coputers choice ->
//  translated from number to rock, paper, scissors.
let compChoice;
// this variable store the value of the users chice
let userChoice;

// Here the variables for the dom elements is created
const rockButton = document.querySelector(".rock");
const paperButton = document.querySelector(".paper");
const scissorsButton = document.querySelector(".scissors");
const player1 = document.querySelector("#player1");
const player2 = document.querySelector("#player2");
const lose = document.querySelector("#lose");
const win = document.querySelector("#win");
const draw = document.querySelector("#draw");

// This function is called when the site loads
window.addEventListener("load", function () {
  // Adds the eventlistener to the rock button
  rockButton.addEventListener("click", () => {
    // makes sure that user choice is = rock
    userChoice = "rock";
    // calls the function ranNumGen which generates a random number between 1-3
    ranNumGen();
    // makes sure that win, lose and draw texts are hidden
    lose.classList.add("hidden");
    win.classList.add("hidden");
    draw.classList.add("hidden");
    // ads shake class to player1
    player1.classList.add("shake");
    // waits for animation to end, then call the function compChooses
    player1.addEventListener("animationend", compChooses);
    // ads shake class to player2
    player2.classList.add("shake");
    // waits for animation to end, then call the function userChooses
    player2.addEventListener("animationend", userChooses);

    // makes sure to reset both player hands by removing the class "rock", "paper", or "scissors"
    player1.classList.remove("rock", "paper", "scissors");
    player2.classList.remove("rock", "paper", "scissors");
  });

  // Adds the eventlistener to the paper button
  paperButton.addEventListener("click", () => {
    // makes sure that user choice is = paper
    userChoice = "paper";
    // calls the function ranNumGen which generates a random number between 1-3
    ranNumGen();
    // makes sure that win, lose and draw texts are hidden
    lose.classList.add("hidden");
    win.classList.add("hidden");
    draw.classList.add("hidden");
    // ads shake class to player1
    player1.classList.add("shake");
    // waits for animation to end, then call the function compChooses
    player1.addEventListener("animationend", compChooses);
    // ads shake class to player2
    player2.classList.add("shake");
    // waits for animation to end, then call the function userChooses
    player2.addEventListener("animationend", userChooses);
    // makes sure to reset both player hands by removing the class "rock", "paper", or "scissors"
    player1.classList.remove("rock", "paper", "scissors");
    player2.classList.remove("rock", "paper", "scissors");
  });

  // Adds the eventlistener to the scissors button
  scissorsButton.addEventListener("click", () => {
    // makes sure that user choice is = scissors
    userChoice = "scissors";
    // calls the function ranNumGen which generates a random number between 1-3
    ranNumGen();
    // makes sure that win, lose and draw texts are hidden
    lose.classList.add("hidden");
    win.classList.add("hidden");
    draw.classList.add("hidden");
    // ads shake class to player1
    player1.classList.add("shake");
    // waits for animation to end, then call the function compChooses
    player1.addEventListener("animationend", compChooses);
    // ads shake class to player2
    player2.classList.add("shake");
    // waits for animation to end, then call the function userChooses
    player2.addEventListener("animationend", userChooses);
    // makes sure to reset both player hands by removing the class "rock", "paper", or "scissors"
    player1.classList.remove("rock", "paper", "scissors");
    player2.classList.remove("rock", "paper", "scissors");
  });
});

// got it from chat gpt with this promt: "give me a js function, that gives ->
// me a random number bewteen 1 and 3, but includes 1 and 3."
// generates a random number between 1-3 and includes 1 and 3.
function ranNumGen() {
  // compNum is set equal to the random number
  compNum = Math.floor(Math.random() * 3) + 1;
}

// translates the random number to rock, paper, or scissors, and sets  ->
// compChoice equal to the choice which fits the number
function compChooses() {
  // if the number is 1 it means rock
  if (compNum == 1) {
    compChoice = "rock";
    // adds the class rock to player2 to show its choice
    player2.classList.add("rock");
  }
  // if the number is 2 it means paper
  else if (compNum == 2) {
    compChoice = "paper";
    // adds the class paper to player2 to show its choice
    player2.classList.add("paper");
  } else {
    // if the number is 3 it means scissors
    compChoice = "scissors";
    // adds the class scissors to player2 to show its choice
    player2.classList.add("scissors");
  }
}

// depending on the value of userChoice this function either adds the class rock, paper or scissors ->
// to player1 in order to show the players choice.
function userChooses() {
  if (userChoice == "rock") {
    player1.classList.add("rock");
  } else if (userChoice == "paper") {
    player1.classList.add("paper");
  } else {
    player1.classList.add("scissors");
  }

  // calls the function compareChoises
  compareChoices();
}

// the main functionality of this function is to compare the userChoice to compChoice in order ->
// to see who won the round.
function compareChoices() {
  // makes sure to remove the class shake from both players, so it can be put on again in next round
  player1.classList.remove("shake");
  player2.classList.remove("shake");

  // sets the rules for all senarios and depending if the user wins or looses it removes the class ->
  // hidden from win or lose. if its a draw it removes the class hidden from draw.
  if (userChoice == "rock" && compChoice == "scissors") {
    win.classList.remove("hidden");
  }

  if (userChoice == "paper" && compChoice == "rock") {
    win.classList.remove("hidden");
  }

  if (userChoice == "scissors" && compChoice == "paper") {
    win.classList.remove("hidden");
  }
  if (userChoice == compChoice) {
    draw.classList.remove("hidden");
    console.log("Draw");
  }
  if (compChoice == "rock" && userChoice == "scissors") {
    lose.classList.remove("hidden");
  }
  if (compChoice == "paper" && userChoice == "rock") {
    lose.classList.remove("hidden");
  }
  if (compChoice == "scissors" && userChoice == "paper") {
    lose.classList.remove("hidden");
  }
}
